Omar tests and funct
Anthony-Alagna/361Project pull request #66
Opened 2023-05-17 23:49 UTC by OmarAbu

2023-05-17 23:54 UTC, kmaule15 approved these changes

2023-05-17 23:54 UTC, BrandonBuckner approved these changes
Looks good

2023-05-18 00:05 UTC, Anthony-Alagna requested changes

2023-05-18 00:05 UTC, Anthony-Alagna commented on README.md
> +mv template..env prod..env
This is also not correct

2023-05-18 00:05 UTC, Anthony-Alagna commented on tests/test_create_delete_section.py
are these tests failing?

2023-05-18 00:26 UTC, OmarAbu commented on tests/test_create_delete_section.py
i was fixing them but then the myapp.email thing came up while iw as testing, but functionality was fine before

2023-05-18 02:07 UTC, closed without merging